[program:azan_service]
; The name of the program as Supervisor sees it

directory=/home/username/project       ; <-- Change to your project directory
command=/home/username/project/.venv/bin/python azan_service.py
autostart=true
autorestart=true
startretries=3

; Redirect stdout/stderr to log files
stdout_logfile=/home/username/project/logs/azan_service.log
stderr_logfile=/home/username/project/logs/azan_service_err.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB
stdout_logfile_backups=3
stderr_logfile_backups=3

; Run as a specific user (important if using audio)
user=username                            ; <-- replace with your Linux user
environment=PATH="/home/username/project/.venv/bin:%(ENV_PATH)s"
